
#server-port
server:
  port: 8000

spring:
  # naming
  application:
    name: "currency-exchange"

  # config-server
  config:
    import: "optional:configserver:http://localhost:8888"

  # h2-db
  h2:
    console:
      enabled: true
  datasource:
    url: "jdbc:h2:mem:testDB"

  # spring-data-jpa
  jpa:
    defer-datasource-initialization: true
    show-sql: true

# eureka-client-registration
eureka:
  client:
    serviceUrl:
      defaultZone: "http://localhost:8761/eureka"

resilience4j:
  # retries
  retry:
    instances:
      sampleApi:
        maxRetryAttempts: 5
        waitDuration: 1s
        EnableExponentialBackoff: true

  # failure threshold
  circuitbreaker:
    instances:
      default:
        failureRateThreshold: 90

  # setting limit to controller endpoint
  ratelimiter:
    instances:
      default:
        limitForPeriod: 2
        limitRefreshPeriod: 10s

  bulkhead:
    instances:
      default:
        maxConcurrentCalls: 10
